"""Sample product catalog data for an electronics store."""
from app.models.product import Product


def get_seed_products() -> list[Product]:
    """Return sample electronics products."""
    return [
        Product(
            id="prod_pixel9pro",
            name="Google Pixel 9 Pro",
            description="6.3-inch OLED, Tensor G4, 16GB RAM, 256GB, 50MP triple camera with AI features",
            price_paise=10999900,
            category="smartphones",
            tags=["phone", "android", "flagship", "ai", "camera"],
            stock=25,
            sku="PIX9PRO-256-BLK",
            image_url="https://example.com/images/pixel9pro.jpg",
        ),
        Product(
            id="prod_pixel9",
            name="Google Pixel 9",
            description="6.3-inch OLED, Tensor G4, 12GB RAM, 128GB, 50MP dual camera",
            price_paise=7999900,
            category="smartphones",
            tags=["phone", "android", "mid-range", "camera"],
            stock=40,
            sku="PIX9-128-GRN",
            image_url="https://example.com/images/pixel9.jpg",
        ),
        Product(
            id="prod_buds_pro",
            name="Pixel Buds Pro 2",
            description="Active noise cancellation, 12h battery, Tensor A1 chip, IPX4",
            price_paise=2299900,
            category="audio",
            tags=["earbuds", "wireless", "anc", "bluetooth"],
            stock=60,
            sku="PBPRO2-CHR",
            image_url="https://example.com/images/buds_pro2.jpg",
        ),
        Product(
            id="prod_buds_a",
            name="Pixel Buds A-Series",
            description="Comfortable fit, 5h battery, hands-free Google Assistant",
            price_paise=999900,
            category="audio",
            tags=["earbuds", "wireless", "budget", "bluetooth"],
            stock=100,
            sku="PBA-OLV",
            image_url="https://example.com/images/buds_a.jpg",
        ),
        Product(
            id="prod_case_pixel9",
            name="Pixel 9 Silicone Case",
            description="Official Google silicone case, MagSafe compatible, microfiber lining",
            price_paise=299900,
            category="accessories",
            tags=["case", "pixel9", "protection", "silicone"],
            stock=80,
            sku="CASE-PIX9-MINT",
            image_url="https://example.com/images/case_pixel9.jpg",
        ),
        Product(
            id="prod_case_pixel9pro",
            name="Pixel 9 Pro Clear Case",
            description="Transparent protective case with shock-absorbing corners",
            price_paise=249900,
            category="accessories",
            tags=["case", "pixel9pro", "protection", "clear"],
            stock=70,
            sku="CASE-PIX9P-CLR",
            image_url="https://example.com/images/case_pixel9pro.jpg",
        ),
        Product(
            id="prod_charger_30w",
            name="30W USB-C Fast Charger",
            description="30W USB-C PD charger, compact design, energy efficient",
            price_paise=299900,
            category="chargers",
            tags=["charger", "usb-c", "fast-charging", "30w"],
            stock=120,
            sku="CHG-30W-WHT",
            image_url="https://example.com/images/charger_30w.jpg",
        ),
        Product(
            id="prod_charger_wireless",
            name="Pixel Stand (2nd Gen)",
            description="Wireless charging stand with fan cooling, up to 23W charging",
            price_paise=799900,
            category="chargers",
            tags=["charger", "wireless", "stand", "qi"],
            stock=30,
            sku="PXSTAND2-WHT",
            image_url="https://example.com/images/pixel_stand2.jpg",
        ),
        Product(
            id="prod_cable_usbc",
            name="USB-C to USB-C Cable (2m)",
            description="Braided USB-C cable, 100W PD, USB 3.2 data transfer",
            price_paise=199900,
            category="accessories",
            tags=["cable", "usb-c", "charging", "data"],
            stock=200,
            sku="CABLE-CC-2M",
            image_url="https://example.com/images/cable_usbc.jpg",
        ),
        Product(
            id="prod_watch3",
            name="Pixel Watch 3",
            description="41mm AMOLED, Wear OS, heart rate, SpO2, GPS, swim-proof",
            price_paise=3999900,
            category="wearables",
            tags=["watch", "smartwatch", "fitness", "health"],
            stock=35,
            sku="PWATCH3-41-SLV",
            image_url="https://example.com/images/pixel_watch3.jpg",
        ),
        Product(
            id="prod_screen_protector",
            name="Pixel 9 Tempered Glass Screen Protector",
            description="9H hardness, oleophobic coating, bubble-free installation",
            price_paise=99900,
            category="accessories",
            tags=["screen-protector", "pixel9", "tempered-glass"],
            stock=150,
            sku="SP-PIX9-TG",
            image_url="https://example.com/images/screen_protector.jpg",
        ),
        Product(
            id="prod_tablet",
            name="Pixel Tablet",
            description="10.95-inch display, Tensor G2, 8GB RAM, 128GB, with Charging Speaker Dock",
            price_paise=4499900,
            category="tablets",
            tags=["tablet", "android", "smart-home", "dock"],
            stock=15,
            sku="PTAB-128-PRC",
            image_url="https://example.com/images/pixel_tablet.jpg",
        ),
    ]
